export const mateLogWhoAmICategories = [
  {
    mateLogTitle: 'Ice Fishing Essentials',
    mateLogWords: [
      'Ice auger',
      'Tip-up',
      'Jigging rod',
      'Ice shelter',
      'Ice hole',
      'Skimmer scoop',
      'Ice cleats',
      'Safety picks',
      'Spud bar',
      'Bait bucket',
      'Tackle box',
      'Fish finder',
      'Wind chill',
      'Slush',
      'First ice',
    ],
  },
  {
    mateLogTitle: 'Fish Species',
    mateLogWords: [
      'Perch',
      'Pike',
      'Walleye',
      'Zander',
      'Trout',
      'Carp',
      'Catfish',
      'Bream',
      'Roach',
      'Tench',
      'Salmon',
      'Bass',
      'Smelt',
      'Sturgeon',
      'Eel',
    ],
  },
  {
    mateLogTitle: 'Baits, Lures & Actions',
    mateLogWords: [
      'Jig',
      'Spoon lure',
      'Hook',
      'Sinker',
      'Swivel',
      'Bobber',
      'Fishing line',
      'Knot',
      'Live bait',
      'Waxworm',
      'Bloodworm',
      'Minnow bait',
      'Hook set',
      'Reeling in',
      'Catch and release',
    ],
  },
  {
    mateLogTitle: 'Funny & Ice Vibes',
    mateLogWords: [
      'Hot cocoa',
      'Thermos',
      'Frozen eyelashes',
      'Hand warmers',
      'Just one more hole',
      'Secret spot',
      'Lucky lure',
      'Tall tale',
      'Snack break',
      'Silent bite',
      'Tangled line',
      'The one that got away',
      'Windy face',
      'Frozen fingers',
      'Ice nap (accidental)',
    ],
  },
];

